config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    # For details on the DSL available within this file, see
    #resources :resource_As 元記事には存在したがこれを記入するとエラーが発生するのでコメントアウト
  end
  devise_for :admins, skip: :all
  #devise_scope :admin do
    # get 'admins/sign_in' => 'admins/sessions#new', as: :new_admin_session
    # post 'admins/sign_in' => 'admins/sessions#create', as: :admin_session
    # delete 'logout' => 'admins/sessions#destroy', as: :destroy_admin_session
  #end
  #(本来は不要である記述だが、細かい修正を行っている中で必要になる場合もあった物の為、コメントアウトに。)

  devise_for :admins, controllers: {
    #sessions:      'admins/sessions',
    #passwords:     'admins/passwords',（無くても良いが念のためコメントアウト）
    registrations: 'admins/registrations'
  }

  namespace :admin do
    root 'homes#top'
    resources :posts,only: [:index,:show]
    resources :genres,only: [:index,:create,:edit,:update]
    resources :post_users,only: [:index,:show,:edit,:update]
  end

  devise_for :post_users, controllers: {
    omniauth_callbacks: 'post_users/omniauth_callbacks',
    sessions:      'post_users/sessions',
    passwords:     'post_users/passwords',
    registrations: 'post_users/registrations'
  }

  scope module: 'public' do
    root 'homes#top'
    get '/search' => 'search#search'
    get '/about', to: 'homes#about'
    get 'post_users/my_page', to: 'post_users#show'
    get 'post_users/unsubscribe', to: 'post_users#unsubscribe'
    patch 'post_users/withdrawal', to: 'post_users#withdrawal', as: 'withdrawal'

    get '/posts/complete', to: 'posts#complete', as: 'complete'

    resources :post_users, only: [:index, :show, :edit, :update]

    resources :posts, only: [:new, :edit, :create, :index, :show, :destroy,:update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
    end

    resources :contacts, only: [:new, :create]
    post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
    post 'contacts/back', to: 'contacts#back', as: 'back'
    get 'done', to: 'contacts#done', as: 'done'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # namespace :admin do
  #   resources :posts, only: [:new, :create, :edit, :update]
  #   resources :post_users, only: [:index, :show, :edit, :update]
  # end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_status.rb
class AdminStatus < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :post_user_id, uniqueness: { scope: :post_id }
  belongs_to :post_user, optional: true
  belongs_to :post

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :post_user, optional: true
    belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :post_user, optional: true
	belongs_to :genre
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
    has_many :bookmarks, dependent: :destroy
    validates :title, presence: true
    validates :genre_id, presence: true
    validates :post_detail, presence: true
    validates :post_detail, length: { minimum: 1 }
    attachment :image

    def bookmarked_by?(post_user)
        bookmarks.where(post_user_id: post_user).exists?
    end

    def favorited_by?(post_user)
        favorites.where(post_user_id: post_user.id).exists?
    end

    # def self.search(search, word)
    #     if search == "forward_match"
    #         @post = Post.where("title LIKE?","#{word}%")
    #     elsif search == "backward_match"
    #         @post = Post.where("title LIKE?","%#{word}")
    #     elsif search == "perfect_match"
    #         @post = Post.where(title: "#{word}")
    #     elsif search == "partial_match"
    #         @post = Post.where("title LIKE?","%#{word}%")
    #     else
    #         @post = Post.all
    #     end
    #    上記の物は以前の完全、前方、後方、完全、部分一致の検索に使用した物。wordかsearchか。

    def self.search(title)
        return all unless title
        where('title LIKE(?)', "%#{title}%")
    end
    # def self.search(search)
    #     return Post.all unless search
    #     Post.where('title LIKE(?)', "%#{search}%") 修正前のコード。比較対象として残しておく
    # end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :post_user, optional: true
    belongs_to :post
    validates :comment, presence: true
end

app/models/post_user.rb
class PostUser < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image, destroy: false
  validates :nickname, length: { minimum: 2, maximum: 20 }
  validates :nickname, presence: true
  validates :introduction, length: { maximum: 50 }

  # def self.from_omniauth(auth)       # snsから取得した、providerとuidを使って、既存ユーザーを検索
  #   sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
  #   # sns認証したことがあればアソシエーションで取得、なければSns_credentialsテーブルにレコード作成

  # # snsのpost_user or post_usersテーブルに対し、SNS認証で取得したメールアドレスが登録済みの場合は、取得 or なければビルド(保存はしない)
  #   post_user = sns.post_user || User.where(email: auth.info.email).first_or_initialize(
  #     nickname: auth.info.nickname,
  #     email: auth.info.email
  #   )
  #   if post_user.persisted?   # post_userが登録済みの場合：そのままログインするため、snsのpost_user_idを更新しとく
  #     sns.post_user = post_user
  #     sns.save
  #   end
  #   { post_user: post_user, sns: sns }   # post_user、snsをハッシュで返す(コントローラーがこれを受け取る)
  # end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # deviseのuserカラムに name を追加している場合は以下のコメントアウトも追記します
      user.nickname = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]


end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_users_helper.rb
module PostUsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id = footer>

  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p class="footer-text">CopyRight The/LifeHacker</p>
        <% if post_user_signed_in? %>
          <div class="footer-link"><%= link_to "お問い合わせはこちらまで", new_contact_path, class: 'text-dark' %></div>
          <!--何かしらフッターに情報を追加してレイアウトを修正する場合用-->
          <!--<div class="collapse navbar-collapse text-white">-->
          <!--  <ul class="navbar-nav ml-auto text-white" >-->
          <!--    <li class="nav-post">-->
          <!--      <#%= link_to "#{t('layout._header.mypage')}", post_users_my_page_path, class: 'text-white' %>-->
          <!--    </li>-->
          <!--    <li class="nav-post">-->
          <!--      <#%= link_to "#{t('layout._header.lifehack')}", posts_path, class: 'text-white' %>-->
          <!--    </li>-->
          <!--    <li class="nav-post">-->
          <!--      <#%= link_to "#{t('layout._header.logout')}", destroy_post_user_session_path, method: :delete, class: 'text-white' %>-->
          <!--    </li>-->
          <!--    <li class="nav-post">-->
          <!--      <#%= link_to "#{t('layout._header.new_post')}", new_post_path, class: 'text-white' %>-->
          <!--    </li>-->
          <!--  </ul>-->
          <!--</div>-->
          <!--<#% else %>-->
          <!--  <div class="collapse navbar-collapse" id="navbarsExample02">-->
          <!--    <ul class="navbar-nav ml-auto">-->
          <!--      <li class="nav-post"><#%= link_to ' about', about_path, class: 'text-white' %></li>-->
          <!--      <li class="nav-post"><#%= link_to "#{t('layout._header.lifehack')}", posts_path , class: 'text-white' %></li>-->
          <!--      <li class="nav-post"><#%= link_to "#{t('layout._header.signup')}", new_post_user_registration_path, class: 'text-white' %></li>-->
          <!--      <li class="nav-post"><#%= link_to "#{t('layout._header.login')}", new_post_user_session_path, class: 'text-white' %></li>-->
          <!--    </ul>-->
          <!--  </div>-->
          <% end %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">
    <div class="container">
      <a class="navbar-brand" href="/"><span>The/LifeHackers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
      </button>
      <% if admin_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav ml-auto">
          <li class="nav-post active">
            <%= link_to "#{t('layout._header.lifehack')}", admin_posts_path,class: 'nav-link text-light' %>
          </li>
          <li class="nav-post">
            <%= link_to "#{t('layout._header.users')}",admin_post_users_path,class: 'nav-link text-light' %>
          </li>
                <li class="nav-post">
            <%= link_to t('layout._header.genres'), admin_genres_path, class: 'nav-link text-light' %>
          </li>
          <li class="nav-post">
            <%= link_to "#{t('layout._header.logout')}", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <nav class="bg-warning">
      <div class="container">
        <div class="navbar-nav ml-auto">
            <% elsif post_user_signed_in? %>
              <div class="collapse navbar-collapse text-white" id="navbarsExample02">
                <%= "ようこそ、 " + post_user.nickname + "さん!" %>
                <ul class="navbar-nav ml-auto text-white" >
                  <li class="nav-post">
                    <%= link_to "#{t('layout._header.mypage')}", post_users_my_page_path, class: 'text-white' %>
                  </li>
                  <li class="nav-post">
                    <%= link_to "#{t('layout._header.lifehack')}", posts_path, class: 'text-white' %>
                  </li>
                  <li class="nav-post">
                    <%= link_to "#{t('layout._header.logout')}", destroy_post_user_session_path, method: :delete, class: 'text-white' %>
                  </li>
                  <li class="nav-post">
                    <%= link_to "#{t('layout._header.new_post')}", new_post_path, class: 'text-white' %>
                  </li>
                </ul>
              </div>
            <% else %>
              <div class="collapse navbar-collapse" id="navbarsExample02">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-post"><%= link_to ' about', about_path, class: 'text-white' %></li>
                  <li class="nav-post"><%= link_to "#{t('layout._header.lifehack')}", posts_path , class: 'text-white' %></li>
                  <li class="nav-post"><%= link_to "#{t('layout._header.signup')}", new_post_user_registration_path, class: 'text-white' %></li>
                  <li class="nav-post"><%= link_to "#{t('layout._header.login')}", new_post_user_session_path, class: 'text-white' %></li>
                </ul>
              </div>
            <% end %>
        </div>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>LifeHackers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <%= render 'layouts/header', { post_user: current_post_user} %>
    </header>
    <main>
      <p><%= flash[:notice] %></p>
      
      <%= yield %>
    </main>
    <footer><%= render 'layouts/footer', { post_user: current_post_user} %></footer>
  </body>
</html>